"""Card-game specific extensions for rl_card_lib."""

from rl_card_lib.cardgames.card import Card, Suit, Rank
from rl_card_lib.cardgames.deck import Deck
from rl_card_lib.cardgames.player import Player
from rl_card_lib.cardgames.card_game import CardGame
from rl_card_lib.cardgames.rules import (
    is_same_suit,
    is_same_color,
    is_same_rank,
    is_higher_than,
    is_lower_than,
    is_adjacent_rank,
    is_next_higher,
    is_next_lower,
    is_alternating_color,
    is_strictly_increasing,
    is_strictly_decreasing,
    is_consecutive_increasing,
    is_consecutive_decreasing,
    is_same_suit_sequence,
    is_alternating_colors_sequence,
    count_by_color,
    count_by_suit,
    count_by_rank,
    count_face_up,
    count_face_down,
    filter_by_suit,
    filter_by_color,
    has_card,
    top_card,
    bottom_card,
    is_standard_deck,
    can_stack_alternating_descending,
    can_stack_same_suit_ascending,
    multiset_counts,
)

__all__ = [
    "Card",
    "Suit",
    "Rank",
    "Deck",
    "Player",
    "CardGame",
    "is_same_suit",
    "is_same_color",
    "is_same_rank",
    "is_higher_than",
    "is_lower_than",
    "is_adjacent_rank",
    "is_next_higher",
    "is_next_lower",
    "is_alternating_color",
    "is_strictly_increasing",
    "is_strictly_decreasing",
    "is_consecutive_increasing",
    "is_consecutive_decreasing",
    "is_same_suit_sequence",
    "is_alternating_colors_sequence",
    "count_by_color",
    "count_by_suit",
    "count_by_rank",
    "count_face_up",
    "count_face_down",
    "filter_by_suit",
    "filter_by_color",
    "has_card",
    "top_card",
    "bottom_card",
    "is_standard_deck",
    "can_stack_alternating_descending",
    "can_stack_same_suit_ascending",
    "multiset_counts",
]
